# Generated by Django 4.2.6 on 2023-12-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('images', models.ImageField(blank=True, upload_to='images')),
                ('mp3_file', models.FileField(upload_to='mp3_files')),
            ],
        ),
    ]
