# Generated by Django 5.0 on 2023-12-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default='Ваше значение по умолчанию', max_length=255),
        ),
    ]
